version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Validating terraform files
          command: |
            cd terraform
            terraform init -backend=false
            terraform validate
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Install wget & unzip
          command: |
            apt-get install wget
            apt-get install unzip
      - run:
          name: Preparing machine to run terraform along with cloud-sdk
          command: |
            wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
            unzip terraform_0.12.24_linux_amd64.zip
      - run:
          name: Building Cloud Infra
          command: |
            cd terraform
            cat <<EOF > creds.json
            $GCP_CREDS
            EOF
            export GOOGLE_APPLICATION_CREDENTIALS="creds.json"
            gcloud auth activate-service-account --key-file=creds.json
            gcloud container clusters get-credentials "${CLUSTER_NAME}" --region ${CLUSTER_REGION} --project ${GCP_PROJECT}
            cat backend.tf
            terraform init
            terraform plan -out "tf.plan"
            terraform apply -auto-approve "tf.plan"
            rm "tf.plan"
            rm creds.json

workflows:
  version: 2
  validate-and-build:
    jobs:
      - validate
      - build:
          requires:
            - validate
          filters:
            branches:
              only: master
