version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Validating terraform files
          command: |
            cd terraform
            terraform init -backend=false
            terraform validate
  build:
    docker:
      - image: japrakash/cci-terraform-light-gcloudsdk:0.0.1
    steps:
      - checkout
      - run:
          name: Building Cloud Infra
          command: |
            cd terraform
            cat <<EOF > creds.json
            $GCP_CREDS
            EOF
            export GOOGLE_APPLICATION_CREDENTIALS="creds.json"
            gcloud auth activate-service-account --key-file=creds.json
            cat backend.tf
            terraform init
            terraform plan -out "tf.plan"
            terraform apply -auto-approve "tf.plan"
            gcloud container clusters get-credentials "${CLUSTER_NAME}" --region ${CLUSTER_REGION} --project ${TF_VAR_project_id}
            rm "tf.plan"
            rm creds.json

workflows:
  version: 2
  validate-and-build:
    jobs:
      - validate
      - build:
          requires:
            - validate
          filters:
            branches:
              only: master
