version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Validate files
          command: |
            cd terraform
            terraform init -backend=false
            terraform validate
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Build infra
          command: |
            cd terraform
            cat <<EOF > creds.json
            $GCP_CREDS
            EOF
            export GOOGLE_APPLICATION_CREDENTIALS="creds.json"
            cat backend.tf
            terraform init
            terraform plan -out "tf.plan"
            terraform apply -auto-approve "tf.plan"
            rm "tf.plan"
            rm creds.json

workflows:
  version: 2
  validate-and-apply:
    jobs:
      - validate
      - build:
          requires:
            - validate
          filters:
            branches:
              only: master
