version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Validate Infra
          commands:
            - sh ./scripts/validate.sh
  build:
    docker:
      - image: japrakash/cci-terraform-light-gcloudsdk:0.0.1
    steps:
      - checkout
      - run:
          name: Build Infra
          commands:
            - sh ./scripts/build.sh
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Deploy Infra
          commands:
            - sh ./scripts/deploy.sh

workflows:
  version: 2
  validate-build-deploy:
    jobs:
      - validate
      - build:
          requires:
            - validate
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

