apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: demo-crt
spec:
  secretName: demo-crt
  dnsNames:
    - testmynewapplication.tk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - testmynewapplication.tk
  issuerRef:
    name: letsencrypt-demo
    kind: ClusterIssuer
